### PR TITLE
WIP: Support LLVM 18

### PR DESCRIPTION
**Pull request by xermicus**
## Description

Support [LLVM 18](https://releases.llvm.org/18.1.0/docs/ReleaseNotes.html#id26).

## Related Issue

#482

## Checklist

- [x] Introduce feature flags 
- [ ] Wait out
  - [x] next `llvm-sys` release supporting LLVM 18
  - [ ] LLVM 18 binary releases to run tests on CI
- [x] Guard removed API methods and make test suite pass
- [ ] Implement added functionality
  - [x] Getting and setting tail, musttail, and notail attributes on call instructions
  - [x] Implmented a safe wrapper around LLVMCreateTargetMachineWithOptions
  - [x] New flags: LLVMGetNNeg, LLVMSetNNeg, LLVMGetIsDisjoint, LLVMSetIsDisjoint, LLVMGetFastMathFlags, LLVMSetFastMathFlags, LLVMCanValueUseFastMathFlags
  - [ ] ~~Operand Bundles~~ We don't need this right now, can I leave this open for a future PR?

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by vcfxb** [comment]
After a [little poke](https://gitlab.com/taricorp/llvm-sys.rs/-/issues/62#note_1818376428), llvm-sys now has updated to support LLVM 18

**Comment by xermicus** [comment]
Great, now I'm basically just waiting for an [ubuntu build](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.1) to use on CI

**Comment by TheDan64** [comment]
@xermicus wdym by the binarys? Tests seem to be working. Or was this an intermittent thing?

**Review by TheDan64 — APPROVED** [review]
Thanks!

**Comment by TheDan64** [comment]
Oh, there's no build check for LLVM 18, could you please add one @xermicus

**Comment by xermicus** [comment]
@TheDan64 yep I have it on my radar

**Comment by Pat-Lafon** [comment]
Brew just got LLVM 18, so maybe this has tricked through the ecosystem now?

**Pull request merged**
