### PR TITLE
workflows: test against LLVM 18.1

### PR DESCRIPTION
**Pull request by airwoodix**
## Description

Add a matrix entry for LLVM 18.1 in the testing workflow.

Requires updating to [KyleMayes/install-llvm-action](https://github.com/KyleMayes/install-llvm-action) [v2.0.2+](https://github.com/KyleMayes/install-llvm-action/releases/tag/v2.0.2). Breaking *API* changes from [v2.0.0](https://github.com/KyleMayes/install-llvm-action/releases/tag/v2.0.0) are not relevant here.

## Related Issue

#482, https://github.com/TheDan64/inkwell/pull/524#issuecomment-2289285489

## How This Has Been Tested

- Partial local run using [nektos/act](https://github.com/nektos/act) to check that the `install-llvm-action` resolves the LLVM version correctly.
- `cargo test -F llvm18-0` with LLVM 18.1.8 libraries.
- Fork pipeline: https://github.com/airwoodix/inkwell/actions/runs/10459452802

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by TheDan64** [comment]
Changes look good to me but tests are not passing

**Comment by airwoodix** [comment]
I was a bit fast reading the changelog for v2.0.0 in `install-llvm-action`. The API changes are not breaking the use here. However, support for LLVM < 7.1 was dropped in KyleMayes/install-llvm-action#64.

7734b55 removes LLVM 4-6 from the testing matrix and bumps to 7.1 for the 7 series. Would this be acceptable?

**Comment by airwoodix** [comment]
Done in a25308b.

`uses` apparently doesn't support (ternary) expressions, so the "Install LLVM and Clang" step is duplicated, with exclusive pre-conditions.

**Review by TheDan64 — APPROVED** [review]
Thank you!

**Pull request merged**
