### PR TITLE
chore: Run `rustfmt`

### PR DESCRIPTION
**Pull request by Hywan**
# Description

This patch is the result of running `rustfmt **/*.rs` from the root of
this project. The goal is the following: When a user (like me) edits a
file, the file is automatically formatted on save; which results in
larger diffs than needed. Let's fix the coding styles once and for all
thanks to `rustfmt` :-)!

### CODE REVIEW

**Comment by TheDan64** [comment]
Hi, thanks for the PR. I appreciate the effort but unfortunately it will not be accepted. We already have an open issue here: https://github.com/TheDan64/inkwell/issues/75 which documents that we're waiting for rustfmt 2.0 so that we can use unstable rustfmt features rather than requiring users to have nightly just to format inkwell.

Regarding formatting on save, editors usually allow you to disable format on save on a per-project basis

**Comment by Hywan** [comment]
Yeah, OK. I'm not sure to understand why you don't want to get a clean code base with the current `rustfmt` version, which will format 99% of the code as you expect, but that's your choice :-).

**Comment by TheDan64** [comment]
It should be out relatively soon I hope. There's only one issue left: https://github.com/rust-lang/rustfmt/milestone/8

**Comment by Hywan** [comment]
Good to know :-)!

**Pull request closed without merging**
