### PR TITLE
Add LLVM13 and LLVM14 builds to CI configuration

### PR DESCRIPTION
**Pull request by nbaksalyar**
## Description

Adds LLVM13 and LLVM14 builds to the CI configuration.

## Related Issue

Add continuous integration checks for LLVM13 and LLVM14 #325 

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by nbaksalyar** [comment]
#324 should be merged first I think so that the build error is fixed.

**Comment by TheDan64** [comment]
Could you rebase this please?

**Comment by TheDan64** [comment]
Any luck with this?

**Comment by TheDan64** [comment]
Not sure why this PR isn't working, but I managed to get it working in #280 which also simplifies the CI build. Closing this in favor of that PR

**Pull request closed without merging**
