### PR TITLE
Expose `pub(crate) fn new` constructors for value types

### PR DESCRIPTION
**Pull request by corbanvilla**
## Description

Exposing these constructors is helpful when working with LLVM code which isn't yet part of the C-API.

## Related Issue

- #424
- #366

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by TheDan64 — APPROVED** [review]

**Comment by TheDan64** [comment]
@corbanvilla The newly pub fns need doc comments. Also, `Value::new` should not be pub since it is internal. Once those are fixed we can merged this

**Comment by corbanvilla** [comment]
@TheDan64 apologies for the delay, just added doc comments!

**Comment by TheDan64** [comment]
@corbanvilla there appear to be some merge conflicts that need to be resolved

**Comment by corbanvilla** [comment]
@TheDan64 Could you clarify where you're referring to.... it looks up to date under the files changed tab.

**Comment by TheDan64** [comment]
ah okay it looks like I can do a regular merge instead of a rebase...

**Pull request merged**
