### PR TITLE
Support for multiple LLVM versions, starting with 3.6

### LINKED ISSUE #3: Setup Travis CI for Linux
- [x] Initial Setup
- [ ] Multiple LLVM version setup to support #1

### PR DESCRIPTION
**Pull request by TheDan64**
## Description

* Updated .travis.yml to build one job per supported LLVM version
* Updated .travis.yml to share deployment procedures across jobs via anchors
* Added support for LLVM 3.6

## Related Issue

Updates #1 to officially support LLVM 3.6. Also fixes #3 

## How This Has Been Tested

Travis-CI have been updated to run the full test suite in both LLVM 3.6 & LLVM 3.7. I've also run 3.6 tests locally with success.

## Option\<Breaking Changes\>

There is a breaking change which requires an LLVM version feature flag to be selected. If not provided, it will throw a compile time error pointing to the README.md.

## Checklist

- [x] I have read the [Contributing Guide](CONTRIBUTING.md)

### CODE REVIEW

**Comment by TheDan64** [comment]
Still needs a bit of additional work to throw a compiler error when no llvm version feature is specified and to update the README.md to document how to specify a version.

**Comment by 6A** [comment]
Wouldn't [compile_error!](https://doc.rust-lang.org/std/macro.compile_error.html) be the perfect match for this?

**Comment by TheDan64** [comment]
Yes! I knew it existed, but forgot what it was called. Thanks!

**Comment by TheDan64** [comment]
In case anyone is following this PR; the last remaining piece here is being able to override the llvm-sys version, which I have yet to have been able to figure out how to do successfully. If it's not possible, this will probably have to go on hold and I'll try and get cargo to support the changes if possible and focus on some other part of Inkwell in the mean time.

**Comment by 6A** [comment]
According to the rustc maintainers, right now Cargo cannot do this at all. Considering the few hacks we've tried, and that none of them worked, I think it's safe to say it cannot work yet unless some changes are made to Cargo itself.

Thus, I think we can only work on one version right now... Which raises the question, shall we focus on one version, or blindly add features to other versions as well? If we only focus on one version, then which one?

**Comment by TheDan64** [comment]
Yeah - So I think we can work on more than one, but only have one as a default for Inkwell. I'm leaning towards merging this PR mostly as is (minus/modifying the documentation changes) so that we can keep testing against other LLVM versions in travis and keep working towards supporting other versions as far as this code base is concerned.

As far as the active inkwell version, I'm thinking about slowly updating it to the latest LLVM version(IE decide 3.7 is pretty good as is, and switch to a compilable initial implementation of 3.8, keeping the feature flag stuff for previous versions), since more people will probably want a newer version. This will allow us to have forward progress. It might be a breaking change for anyone currently using inkwell.. though probably not many people are using it yet, and it's better to do so early on.

If someone really needs to use an older version, they can fork or clone a local copy and modify the llvm-sys version and feature flag to the older version, and it should work (will document it). Far from ideal, but I will try and get some support from cargo even if I have to implement it myself haha

**Comment by TheDan64** [comment]
One more option might be to explore if build scripts might be able to help somehow: https://doc.rust-lang.org/cargo/reference/build-scripts.html I don't have any concrete ideas yet, but it might be worth exploring if we could modify inkwell's Cargo.toml that way...

**Comment by TheDan64** [comment]
Like, maybe we could require the user to pass in an environment variable "INKWELL_LLVM_VERSION='3.7'" or so, and the build script would do all of the modifications to the llvm-sys version and feature flags? Glancing through the above docs makes it sound like it might be possible

**Comment by 6A** [comment]
Indeed, build scripts can probably automate ways to achieve our goal, but it might not always be very "graceful." For example, we might be able to edit the dependency in `Cargo.toml` using `build.rs`, and trigger a rebuild thanks to the `rerun-if-changed` parameter.

**Comment by TheDan64** [comment]
build script is starting to look like a no go either. I was able to get the compiler to set the required feature flag pretty easily, but I don't think I can change the required llvm-sys version since dependencies seem to be acquired before the build step. sigh.

**Comment by TheDan64** [comment]
Random idea I had today that I'll log here so I don't forget: The approach we can take is to branch off master, with the only change being the llvm-sys version and default feature flag, and keep them otherwise rebased on master, which has cfgs for different versions.

This would mean we can't release an inkwell version to crates.io when we are ready to do so that includes multiple version support, though. I suppose we can have the crates.io version be hardcoded to the latest version of LLVM(-sys) and anyone desiring an older version of LLVM would be required to point at the appropriate GH branch.

As always, not an ideal approach, but this one would actually work, I think.

**Comment by 6A** [comment]
That sounds great to me, and that might be the only way to go for now, so this isn't a big problem.  
I don't have an example right now, but I know some widely used crates also suggest using the GitHub repo source instead of an hardcoded version on crates.io.

**Pull request merged**
