### PR TITLE
Fix warnings by removing unused imports

### PR DESCRIPTION
**Pull request by nbaksalyar**
## Description

Fix warnings by removing unused imports.
Also fixes the build error that's caused by an unused doc comment.

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by TheDan64** [comment]
I don't really understand why this fixes the linker error? Could you explain?

**Comment by nbaksalyar** [comment]
> I don't really understand why this fixes the linker error? Could you explain?

Hmm, not sure about the linker error. The main fix is this line here:

```rust
     // /// Gets a usable context object with a correct lifetime.
```

It fixes the [rustdoc error](https://github.com/TheDan64/inkwell/runs/6443197385?check_suite_focus=true#step:4:106).

But while at it, I also fixed a bunch of warnings about unused imports.

**Comment by TheDan64** [comment]
Oh I see, I missed that haha

**Review by TheDan64 — APPROVED** [review]
Thanks!

**Pull request merged**
