### PR TITLE
Fix detection of extern functions defined in Rust

### PR DESCRIPTION
**Pull request by OlegTheCat**
## Description

This fixes the ability of Kaleidoscope JIT to detect functions defined in Rust.

## Related Issue

#74 

## How This Has Been Tested

External functions have been tested in Kaleidoscope REPL:

```
?> extern printd(x)

?> printd(10)
10
=> 10

?> extern putchard(x)

?> putchard(33)
!=> 33
```

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by OlegTheCat** [comment]
As discussed in #74, if one tries to execute a function that is not actually defined, it will lead to a segfault:

```
?> extern non_existing(x)

?> non_existing(1)
cargo: warning: cargo crashed, killed by SIGSEGV.
cargo itself has not crashed, but for transparency,
it will now kill itself (without dumping core) with the same signal


warnings can be silenced by the --no-warnings (-n) option
Segmentation fault: 11
```

From @71 [comment](https://github.com/TheDan64/inkwell/issues/74#issuecomment-480912770) it seemed to me that this is acceptable behavior, but I'm not sure that I've got everything right. Let's discuss it here if needed.

**Comment by TheDan64** [comment]
I think the best thing to do would be to see what the C version of Kaleidoscope does - if it also segfaults on unknown extern functions then this is acceptable (and likely a limitation of the LLVM JIT), and if not then there's likely something we need to fix

**Comment by OlegTheCat** [comment]
Yeah, makes sense. I'll try to investigate this thing.

**Comment by OlegTheCat** [comment]
So, the C++ version seems not to segfault, but the issue is that it uses different API for JITting (which is old and deprecated right not, btw). I'm currently struggling to map it to the new API through inkwell <-> llvm-sys <-> llvm-c <-> llvm-c++ chain. It seems I'll need more time to investigate this.

**Pull request merged**
