### PR TITLE
Add support for LoongArch

### PR DESCRIPTION
**Pull request by heiher**
## Description

This PR aims to add support for LoongArch.

## Related Issue

It depends on

- [x] https://gitlab.com/taricorp/llvm-sys.rs/-/merge_requests/33

## How This Has Been Tested

```bash
cargo test --features llvm16-0
```

## Option\<Breaking Changes\>

None

## Checklist

None

### CODE REVIEW

**Comment by heiher** [comment]
@TheDan64 llvm-sys.rs is done, ready for review now. thanks!

**Comment by TheDan64** [comment]
Don't you have to update the min llvm-16 version?

**Comment by heiher** [comment]
Thank you, it's updated now.

**Review by TheDan64 — APPROVED** [review]
Thanks!

**Pull request merged**
