### PR TITLE
Support LLVM 17

### PR DESCRIPTION
**Pull request by vadorovsky**
Fixes: #444

## Description

Add `llvm17-0` feature with LLVM 17 support.

This includes the following LLVM-C API changes:

* Core
  * Removed functions:
    * LLVMContextSetOpaquePointers
    * LLVMConstSelect
* Transforms
  * PassRegistry and pass initialization removed, as they were the part of legacy Pass Manager. This results in complete removal of the following modules:
    * instcombine
    * ipo
    * pass_manager_builder
    * scalar
    * util
    * vectorize
* Debug info
  * New language:
    * Mojo

## Related Issue

#444

## How This Has Been Tested

No additional tests apart from the existing ones.

## Option\<Breaking Changes\>

* Disabled `PassManagerBuilder` for LLVM 17, as it was removed
* Disabled the most of `PassManager` methods, as the corresponding functions were removed.

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Pat-Lafon** [comment]
Update the README 🙏 ?

**Comment by SUPERCILEX** [comment]
Any updates on this?

**Comment by TheDan64** [comment]
@vadorovsky We can merge this once the test suite is fixed to work with other versions

**Comment by novafacing** [comment]
Is anything needed other than to add entries for 17-0 to test.yml to enable CI? I can help out if needed.

**Comment by SUPERCILEX** [comment]
I put out a PR that gets us over the edge. Was just an import typo: https://github.com/TheDan64/inkwell/pull/460

**Comment by SUPERCILEX** [comment]
Ah shoot, spoke too soon. All the tests and examples are broken on llvm 17.

**Comment by vadorovsky** [comment]
Whoops, sorry for lack of reaction! I will try to fix the tests later today.

**Comment by SUPERCILEX** [comment]
That'd be great! You can grab my commit here: [`f5a1771` (#460)](https://github.com/TheDan64/inkwell/pull/460/commits/f5a1771b89036b8d809a0de559c842cfa37eed0c)

Looks like some From conversions are broken: https://github.com/SUPERCILEX/inkwell/actions/runs/7471632843/job/20332249713

**Pull request closed without merging**
