### PR TITLE
Add missing iterators

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Review by TheDan64 — APPROVED** [review]
Thanks!

**Comment by SUPERCILEX** [comment]
Awesome, thanks! Any chance we can get a new release?

**Comment by TheDan64** [comment]
Yes definitely soon, just trying to see if this PR will get finished soon but if not will do one anyway

**Comment by SUPERCILEX** [comment]
Oh didn't see it, sounds good! :heart:

**Comment by TheDan64** [comment]
@SUPERCILEX fyi, just released inkwell 0.3.0

**Comment by SUPERCILEX** [comment]
Awesome, thank you! Though ironically enough this morning I realized I forgot to add an operator iterator. Will send a PR for that in a bit. Sorry!

**Pull request merged**
