### PR TITLE
Add even more iterators

### PR DESCRIPTION
**Pull request by SUPERCILEX**
I think I got them all this time.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Hey, just wanted to double check that there's nothing to do on my end since I've been assigned. Pretty sure that's your standard workflow, but I wanted to make sure you're not waiting on me for something. :)

**Comment by TheDan64** [comment]
You're all set for now, I will review when I have some time

**Review by TheDan64 — APPROVED** [review]
Thanks!

**Comment by SUPERCILEX** [comment]
@TheDan64 Any chance you can make another release?

**Comment by TheDan64** [comment]
Yes, can do at some point soon

**Comment by TheDan64** [comment]
@SUPERCILEX published

**Comment by SUPERCILEX** [comment]
Woohoo, thanks!

**Pull request merged**
