### PR TITLE
Change llvm-sys version from 130.0 to 130.0.1

### PR DESCRIPTION
**Pull request by 82dev**
There was a bug in llvm-sys for users that installed LLVM from MYSYS.

### CODE REVIEW

**Review by TheDan64 — APPROVED** [review]

**Comment by TheDan64** [comment]
Thanks!

**Comment by TheDan64** [comment]
@82dev I'm inclined to merge this, but were you able to run the full test suite with this change? We don't currently have CI set up for LLVM13

**Comment by leifhelm** [comment]
Updating to llvm-sys version 130.0.2 did not break `cargo test --release --features llvm13-0 --verbose` on my system.

**Comment by TheDan64** [comment]
This has already been fixed on master

**Pull request closed without merging**
